### ISSUE TITLE
啟用播放器快速鍵的功能似乎失效了

### ISSUE THREAD

**Issue by i1itione** [mingc00/userscripts#1]
例如按下空白鍵無法實現影片播放 / 暫停，不曉得是 HamiVideo 網站改版的關係，
還是和瀏覽器版本可能也有關？瀏覽器是 Chrome v111。

**Comment by mingc00** [comment]
HamiVideo 把快速鍵修好了，已把相關 code 從 userscript 拿掉，更新 v1.3.2 就會修復。
